import type { Metadata } from "next";
import "./globals.css";
import { Open_Sans } from 'next/font/google';
import { SpeedInsights } from "@vercel/speed-insights/next";

const roboto = Open_Sans({
  subsets: ['latin'],
  weight: ['400', '700'], 
  display: 'swap',
  variable: '--font-roboto'
})

export const metadata: Metadata = {
  title: "Pet Shop - Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={roboto.className}>
        {children}
        <SpeedInsights />
      </body>
    </html>
  );
}
